// This file was generated by update_gamefiles.sh
#pragma once

#include "game/data/sprites/Shantae_Idle_bin.h"
#include "game/data/sprites/debug_font_8x8_bold.h"
#include "game/data/tilemaps/NightSkySet.h"
#include "game/data/tilemaps/UiAtlus.h"

#define ALL_FILES()\
FILE(sprites, Shantae_Idle_bin)\
FILE(sprites, debug_font_8x8_bold)\
FILE(tilemaps, NightSkySet)\
FILE(tilemaps, UiAtlus)\
//
