// This file was generated by update_gamefiles.sh
#pragma once

#include "game/data/sprites/Sagume.h"
#include "game/data/sprites/Shantae_Idle_bin.h"
#include "game/data/sprites/debug_font_8x8_bold.h"
#include "game/data/tilemaps/NightSkySet.h"
#include "game/data/tilemaps/UiAtlus.h"
#include "game/data/tilemaps/bg1.h"
#include "game/data/tilemaps/opening_cutscene_set.h"
#include "game/data/tilemaps/thgj8_bg1.h"

#define ALL_FILES()\
FILE(sprites, Sagume)\
FILE(sprites, Shantae_Idle_bin)\
FILE(sprites, debug_font_8x8_bold)\
FILE(tilemaps, NightSkySet)\
FILE(tilemaps, UiAtlus)\
FILE(tilemaps, bg1)\
FILE(tilemaps, opening_cutscene_set)\
FILE(tilemaps, thgj8_bg1)\
//
