// This file was generated by update_gamefiles.sh
#pragma once

#include "game/data/audio/DmgMidiFallOfFall.h"
#include "game/data/audio/TheCrowSong.h"
#include "game/data/sprites/Shantae_Idle_bin.h"
#include "game/data/sprites/debug_font_8x8_bold.h"
#include "game/data/tilemaps/Eosd.h"
#include "game/data/tilemaps/NightSky.h"
#include "game/data/tilemaps/NightSky_Inverted.h"
#include "game/data/tilemaps/UiAtlus.h"

#define ALL_FILES()\
FILE(audio, DmgMidiFallOfFall)\
FILE(audio, TheCrowSong)\
FILE(sprites, Shantae_Idle_bin)\
FILE(sprites, debug_font_8x8_bold)\
FILE(tilemaps, Eosd)\
FILE(tilemaps, NightSky)\
FILE(tilemaps, NightSky_Inverted)\
FILE(tilemaps, UiAtlus)\
//
