#ifndef PRAGMA_ONCE_ENGINE_GBA_REGISTERS_REGISTERMAP_H
#define PRAGMA_ONCE_ENGINE_GBA_REGISTERS_REGISTERMAP_H

#include "engine/gba/memory/GBAMemoryLocations.h"

#define REG_DISPCNT	(IO_REGISTERS + 0x0)
#define REG_DISPSTAT (IO_REGISTERS + 0x4)
#define REG_VCOUNT (IO_REGISTERS + 0x6)
#define REG_KEYINPUT (IO_REGISTERS + 0x130)

#endif
